version: "3.4"
services:

  central-db:
    container_name: central-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=central-db
      - PGDATA=/var/lib/postgresql/data/pgdata/central-db
